# Generated by Django 6.1.1 on 2026-09-26 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamento',
            new_name='Department',
        ),
    ]
