# Generated by Django 6.1.1 on 2026-09-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_departamento_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='codigo',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='nombre',
            new_name='name',
        ),
    ]
