# Generated by Django 6.1.1 on 2026-09-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id', 'code'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
